require: rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - vendor/bundle/**/*

RSpec/MessageChain:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 14

RSpec/MessageSpies:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*.rb'

RSpec/MissingSuper:
  Exclude:
    - 'entities/*_card.rb'

MultipleMemoizedHelpers:
  Max: 15

RSpec/AnyInstance:
  Enabled: false

Documentation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false
